
services:
  cms:
    image: brettt89/silverstripe-web
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - ./themes:/var/www/html/themes
      - ss-eg-vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
    ports:
      - 9000:80
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - SS_ENVIRONMENT_TYPE=dev
      - SS_DATABASE_CLASS=MySQLDatabase
      - SS_DATABASE_SERVER=database
      - SS_DATABASE_NAME=SS_example_db
      - SS_DATABASE_USERNAME=root
      - SS_DATABASE_PASSWORD=example6_912
      - SS_DEFAULT_ADMIN_USERNAME=admin
      - SS_DEFAULT_ADMIN_PASSWORD=c3_56jmp_456p_x943

  composer:
    image: composer
    volumes:
      - ss-eg-vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
    working_dir: /var/www/html
    command: update

  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example6_912
      - MYSQL_DATABASE=SS_example_db
    volumes:
      - ss-eg-dbdata:/var/lib/mysql

volumes:
  ss-eg-vendor:
  ss-eg-dbdata: